export const THEMES = {
  classic: {
    name: "Classic Minimal",
    preview: "bg-white border-gray-200",
    wrapper: "bg-gray-50 min-h-screen",
    header: "bg-white border-b border-gray-200",
    headerText: "text-gray-900",
    headerSubtext: "text-gray-500",
    categoryBar: "bg-white border-b border-gray-100 sticky top-0 z-10",
    categoryActive: "bg-gray-900 text-white",
    categoryInactive: "bg-gray-100 text-gray-600 hover:bg-gray-200",
    card: "bg-white border border-gray-100 rounded-2xl shadow-sm",
    cardTitle: "text-gray-900",
    cardDesc: "text-gray-500",
    cardPrice: "text-gray-900",
    addBtn: "bg-gray-900 text-white hover:bg-gray-700",
    quantityBtn: "bg-gray-900 text-white",
    cartBtn: "bg-gray-900 text-white hover:bg-gray-800",
  },
  "dark-luxury": {
    name: "Dark Luxury",
    preview: "bg-gray-900 border-yellow-500",
    wrapper: "bg-gray-950 min-h-screen",
    header: "bg-gradient-to-r from-gray-900 to-gray-800 border-b border-yellow-500/30",
    headerText: "text-yellow-400",
    headerSubtext: "text-gray-400",
    categoryBar: "bg-gray-900 border-b border-gray-700 sticky top-0 z-10",
    categoryActive: "bg-yellow-500 text-gray-900",
    categoryInactive: "bg-gray-800 text-gray-400 hover:bg-gray-700",
    card: "bg-gray-900 border border-gray-700 rounded-2xl shadow-lg",
    cardTitle: "text-white",
    cardDesc: "text-gray-400",
    cardPrice: "text-yellow-400",
    addBtn: "bg-yellow-500 text-gray-900 hover:bg-yellow-400 font-bold",
    quantityBtn: "bg-yellow-500 text-gray-900",
    cartBtn: "bg-yellow-500 text-gray-900 hover:bg-yellow-400 font-bold",
  },
  "fresh-green": {
    name: "Fresh Green",
    preview: "bg-green-50 border-green-500",
    wrapper: "bg-green-50 min-h-screen",
    header: "bg-gradient-to-r from-green-600 to-emerald-500",
    headerText: "text-white",
    headerSubtext: "text-green-100",
    categoryBar: "bg-white border-b border-green-100 sticky top-0 z-10",
    categoryActive: "bg-green-600 text-white",
    categoryInactive: "bg-green-50 text-green-700 hover:bg-green-100",
    card: "bg-white border border-green-100 rounded-2xl shadow-sm",
    cardTitle: "text-gray-900",
    cardDesc: "text-gray-500",
    cardPrice: "text-green-600",
    addBtn: "bg-green-600 text-white hover:bg-green-500",
    quantityBtn: "bg-green-600 text-white",
    cartBtn: "bg-green-600 text-white hover:bg-green-500",
  },
  "ocean-blue": {
    name: "Ocean Blue",
    preview: "bg-blue-50 border-blue-500",
    wrapper: "bg-slate-50 min-h-screen",
    header: "bg-gradient-to-r from-blue-700 to-cyan-500",
    headerText: "text-white",
    headerSubtext: "text-blue-100",
    categoryBar: "bg-white border-b border-blue-100 sticky top-0 z-10",
    categoryActive: "bg-blue-600 text-white",
    categoryInactive: "bg-blue-50 text-blue-700 hover:bg-blue-100",
    card: "bg-white border border-blue-100 rounded-2xl shadow-sm",
    cardTitle: "text-gray-900",
    cardDesc: "text-gray-500",
    cardPrice: "text-blue-600",
    addBtn: "bg-blue-600 text-white hover:bg-blue-500",
    quantityBtn: "bg-blue-600 text-white",
    cartBtn: "bg-blue-600 text-white hover:bg-blue-500",
  },
  "warm-sunset": {
    name: "Warm Sunset",
    preview: "bg-orange-50 border-orange-500",
    wrapper: "bg-orange-50 min-h-screen",
    header: "bg-gradient-to-r from-orange-500 to-rose-500",
    headerText: "text-white",
    headerSubtext: "text-orange-100",
    categoryBar: "bg-white border-b border-orange-100 sticky top-0 z-10",
    categoryActive: "bg-orange-500 text-white",
    categoryInactive: "bg-orange-50 text-orange-700 hover:bg-orange-100",
    card: "bg-white border border-orange-100 rounded-2xl shadow-sm",
    cardTitle: "text-gray-900",
    cardDesc: "text-gray-500",
    cardPrice: "text-orange-500",
    addBtn: "bg-orange-500 text-white hover:bg-orange-400",
    quantityBtn: "bg-orange-500 text-white",
    cartBtn: "bg-gradient-to-r from-orange-500 to-rose-500 text-white hover:opacity-90",
  },
  "bold-red": {
    name: "Bold Red",
    preview: "bg-red-50 border-red-600",
    wrapper: "bg-gray-50 min-h-screen",
    header: "bg-gradient-to-r from-red-700 to-red-500",
    headerText: "text-white",
    headerSubtext: "text-red-100",
    categoryBar: "bg-white border-b border-red-100 sticky top-0 z-10",
    categoryActive: "bg-red-600 text-white",
    categoryInactive: "bg-red-50 text-red-700 hover:bg-red-100",
    card: "bg-white border border-red-100 rounded-2xl shadow-sm",
    cardTitle: "text-gray-900",
    cardDesc: "text-gray-500",
    cardPrice: "text-red-600",
    addBtn: "bg-red-600 text-white hover:bg-red-500",
    quantityBtn: "bg-red-600 text-white",
    cartBtn: "bg-red-600 text-white hover:bg-red-500",
  },
}

export function getTheme(themeName) {
  return THEMES[themeName] || THEMES.classic
}